sudo: false
language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - "/^v?[0-9\\.]+/"
cache:
- composer
- "$HOME/.composer/cache"
php:
- 7.0
- 7.2
env:
  global:
    - SVN_REPO: https://plugins.svn.wordpress.org/hagakure
    - secure: "YAVp1gH/tsLkEso55jVpPufuizqbFV9zoAO/R2Q8PhTnIyPrE3c1Kbdgtqe/tq94G58OySzFXpcG6vf8+I/E7Brf/32GaD+VjgmbUJr57sb+fW0bdCKEIV4uM99JKtM9VRkJtsSRydnZerVshw9E6NwrJj7zP53qFTtutCpF5Ewq71/tZhLy93HrV5tenTj7Ah6lQS9dZmEmveGme6GeDwBo+c4ksC7EFXF3WgOqtg2Qc9ytfr0QmK9B5N7z9HE2XmfBvdKlcCopiT1XYy/PJg8nUgmkcfNfXxkWhnTJKZfMS2j+JyAY4b9Rjm4lKC7aonCHf2tqpLHmO8zlEF0h5mztEPY52GGbTpkr8+rVJehE356yuV7geaRH4robOrwV0M5edKQ5+210WFYXvnQNLG9G7VU0j6NcncyNzYnSAqsCwALlkF8qccdDUVcp57lyGjOT0GZGH2GRGKL4vcFchSflvsDuiIJKNQja7apoXFmNBkthhM3Zikbs799pOp/l19qK8NjdqPNgJfCmOegMyfHvx8Npv+mW23x5Jp+ejbb17v0dcuJJxWmzM6Dt+StuuA/kXCkkh41Uv0ZpZr966vjwjFxedyApXlLjHjztuufMdaass8iXymgnKOVgHHNSoTfR3rx8IkJ5dqIhiiX+/8cggZGeCptm9J9Bdu3t+SA="
  matrix:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=5.0 WP_MULTISITE=0
matrix:
  include:
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=0 WP_PULUGIN_DEPLOY=1
before_script:
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- composer install
script:
- composer test
after_success:
- curl -L https://raw.githubusercontent.com/fumikito/wp-readme/master/wp-readme.php | php
- sed -i -e "s/nightly/${TRAVIS_TAG}/" $(basename $TRAVIS_REPO_SLUG).php
- curl https://raw.githubusercontent.com/miya0001/auto-build/master/auto-build.sh | bash
- curl -L https://raw.githubusercontent.com/miya0001/travis2wpplugin/master/deploy.sh | bash
- rm -rf ./build
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Pu8Z9MqvfNyCUBJNP2ToE2TQ/0EXjB7W9EIMit4CAOAd/QvgmckMlMzbFc9Rz2rcFsiQwAAeqr6j1h1JannolIRXVPyee1dC9jjDghcWf5JA3Pstqrl+jfQctrUXwxCAMyMNcZ+wAuCgT0iX9qkBfchIyJHc5GHJpQqZqF4lmbDscfZ4v1yVPZ4df21sayL2kyTuDV8uJu6VTMBOI8ML7t2xY7izRfQB9Xc8bqoR/0zRYqXKmwUlGt2w5UJvUv8m0NfNhTNhE3Gcbg6PqyQbCRw0q481WcdFA1081WwrXmIWqef59F0Y3DMgJoyDdu3+Gw42ZZqHkPqBAPBvRnSf/2Yu+IspfTFF+uU+uvZ3+RQIVcVinbHzN7MnQnmokI13DefUVnvwShqn56958pES54TPasLYNfWExi/YTvunzmm9wskPRwOBUJ2bvLURyvESlxsQJMQ9gw7aLtpZDsN28XP2eo70fJ96+2bhlDA2phYY0k9NPwuUXBsDiixuhU4+PhghoGMNIZumAgkR+EPJtyMe8iR7Gp6QlXYoPxTzWBKPBv5QdIpfZDWdtFr2vIbxh6VNT0djCCifVXA597IdIUVzDJao+urIlh1iWjzkxX5Wc1AEFUXrPQprf7MCHCK+emPFgCL6RK9tRDMQ0hnmWzx9EczYVElCmue93LNQZCQ=
  file: hagakure.zip
  on:
    tags: true
    repo: kuno1/hagakure
